// Demo data — placeholder articles, swap with RSS-fetched data once wired up.
// Shape is normalized: {id, title, excerpt, url, date (ISO), tag, image, readingMin}

window.NOTE_FEED_DEMO = [
  {
    id: 'a1',
    title: '違いを、力に。多国籍チームでプロジェクトを進める3つの問い',
    excerpt: '言葉も時差も背景も違うメンバーが集まったとき、何を最初に揃えるべきか。10年のPM経験から見えてきた、「違い」を成果に変えるための問いを共有します。',
    url: 'https://note.com/tsunagu_proj181',
    date: '2025-10-22',
    tag: 'PM',
    image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&auto=format&fit=crop',
    readingMin: 6,
  },
  {
    id: 'a2',
    title: 'AIに任せること、自分で残すこと — 1日のワークフローを書き出してみた',
    excerpt: 'ChatGPTとClaudeを業務に組み込んで半年。どこまで任せて、どこから手を動かすか。実際のワークフローを公開しながら考えます。',
    url: 'https://note.com/tsunagu_proj181',
    date: '2025-10-15',
    tag: 'AI',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop',
    readingMin: 8,
  },
  {
    id: 'a3',
    title: '30代から始めるライフプラン — 数字で考える「これから20年」',
    excerpt: 'iDeCo、NISA、住宅、教育、老後。漠然とした不安を、具体的な数字とシナリオに置き換えるフレームワークをまとめました。',
    url: 'https://note.com/tsunagu_proj181',
    date: '2025-10-08',
    tag: 'ライフプラン',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop',
    readingMin: 10,
  },
  {
    id: 'a4',
    title: '京都・三千院でAIと考えた、これからの働き方',
    excerpt: '苔むした石段に座って、Claudeに「あなたが思う理想の働き方」を聞いた。返ってきた答えを、人間の側から検証してみる。',
    url: 'https://note.com/tsunagu_proj181',
    date: '2025-09-28',
    tag: '旅',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&auto=format&fit=crop',
    readingMin: 5,
  },
  {
    id: 'a5',
    title: '「つなぐ」の解像度を上げる — プロジェクトマネジメントの語彙',
    excerpt: 'Connect, Bridge, Translate, Mediate, Facilitate — どれも日本語では「つなぐ」と訳されがち。違いを言語化することで、何が見えてくるか。',
    url: 'https://note.com/tsunagu_proj181',
    date: '2025-09-20',
    tag: 'PM',
    image: '',
    readingMin: 7,
  },
  {
    id: 'a6',
    title: 'バンクーバーで見た、ファイナンシャルプランナーの仕事の幅',
    excerpt: 'カナダで会ったFPは、保険も投資も税金も住宅ローンも、一人で見ていた。日本との制度の違いから学べること。',
    url: 'https://note.com/tsunagu_proj181',
    date: '2025-09-12',
    tag: '海外',
    image: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=800&auto=format&fit=crop',
    readingMin: 6,
  },
];
